### ISSUE TITLE
Implement `bbs_database topic-filter`

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#544]
## Context
- We are done implementing `bbs_database topic-extract` for all possible sources (see #525 #533 #535 #540).
- This means that for, each article, we have collected in a `metadata.jsonl` file all the available information about the article and journal topics.

## Goal of this Issue
- The goal of this Issue is to implement article filtering by topic.
- Main idea: determine for each of the articles whether we want to include it (`True`) into our database or not (`False`).
- **Inputs to the command:**
  - the `JSONL` file with the collected metadata info about the article and the journal topics
  - user-defined configurations (e.g. a `YAML` file) to determine which papers should be set to `True` by the filter — e.g. `arXiv` topic should be any of `q-bio.*`
- **Outputs of the command:**
  - a `JSONL` file (or a `CSV` if you want, since it's only two fields per structure really) saying for each file whether we want to keep it (`True`) or not (`False`)

**Comment by FrancescoCasalegno** [comment]
Example of a possible YAML configuration file structure for the `topic-filter`:
```yaml
topics:
    accept:  # note: by default policy is "reject all"
        article:
            arXiv:
                 - q-bio.*
        journal:
            MeSH:
                 - topic_1
                 - topic_2
    reject:
        article:
            arXiv:
                 - q-bio.PE
```
